- name: a playbook to set up my local machine
  hosts: localhost
  connection: local
  roles:
    - common
  vars:
    download_dir: "{{ ansible_env.HOME }}/Downloads"
    local_bin_dir: "{{ ansible_env.HOME }}/.local/bin"
    apps_dir: "{{ ansible_env.HOME }}/Applications"
    zsh_version: '5.4.2'
    tmux_version: '2.6'
    system_type: 'desktop'

  tasks:
    - debug:
        msg: "{{ ansible_env }}"
