- name: clone dotfiles repository
  git:
    repo: git@gitlab.com:ads248/dotfiles.git
    dest: "{{ ansible_env.HOME }}/dotfiles"
    key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    accept_hostkey: yes


- name: remove/backup files before stow
  command: "mv -f {{ ansible_env.HOME }}/{{ item }} {{ ansible_env.HOME }}/{{ item }}.bak"
  with_items:
    - '.bashrc'
    - '.zshrc'
    - '.profile'
    - '.tmux.conf'
  ignore_errors: yes

- name: stow dotfiles
  block:
    - command: stow --no-folding {{ item|quote }}
      args:
        chdir: "{{ ansible_env.HOME }}/dotfiles"
      with_items:
        - common
        - shell
        - vim
        - scripts
        - beets
