# TODO: snap install spotify
#- name: install spotify
#  block:
#    - apt_key:
#        keyserver: 'hkp://keyserver.ubuntu.com:80'
#        id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
#        state: present
#
#    - apt_repository:
#        repo: 'deb http://repository.spotify.com stable non-free'
#        filename: spotify
#        state: present
#
#    - apt:
#        name: spotify-client
#        update_cache: yes
#        state: present
#  become: yes

- name: install lutris
  block:
    - apt_key:
        url: "http://download.opensuse.org/repositories/home:/strycore/xUbuntu_{{ ansible_facts.distribution_version }}/Release.key"
        state: present

    - apt_repository:
        repo: 'deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_{{ ansible_facts.distribution_version }}/ ./'
        filename: lutris
        state: present

    - apt:
        name: lutris
        update_cache: yes
        state: present
  become: yes

- name: "install piper/libratbag"
  block:
    - apt_repository:
        repo: 'ppa:libratbag-piper/piper-libratbag-git'
        state: present

    - apt:
        name: 
          - ratbagd
          - piper
        update_cache: yes
        state: present
  become: yes
  tags:
    - libratbag
    - piper
    - gaming

- name: install calibre
  shell: wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  become: yes

- name: installs via url deb
  apt:
    deb: "{{ item }}"
    state: present
  with_items:
    # RipGrep (deb)
    - 'https://github.com/BurntSushi/ripgrep/releases/download/{{ versions.ripgrep }}/ripgrep_{{ versions.ripgrep }}_amd64.deb'
    # Google Chrome (Stable)
    - 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
    # Vivaldi
    - 'https://downloads.vivaldi.com/snapshot/vivaldi-{{ versions.vivaldi }}_amd64.deb'
    # Spideroak One
    - 'https://spideroak.com/release/spideroak/deb_x64'
    # Google Play Music manager - 'https://dl.google.com/linux/direct/google-musicmanager-beta_current_amd64.deb'
    # keybase
    - 'https://prerelease.keybase.io/keybase_amd64.deb'
  become: yes
  ignore_errors: yes

- name: download Steam deb
  get_url:
    url: https://steamcdn-a.akamaihd.net/client/installer/steam.deb
    dest: "{{ download_dir }}/steam.deb"
