- name: upgrade packages at start
  apt:
    update_cache: yes
    upgrade: full
  become: yes

- name: create local bin directory
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: create cloned Applications directory
  file:
    path: "{{ apps_dir }}"
    state: directory

- name: add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    # latest gnome3
    - 'ppa:gnome3-team/gnome3-staging'

    # latest libreoffice
    - 'ppa:libreoffice/ppa'

    # icon and theme collections
    - 'ppa:noobslab/icons'
    #- 'ppa:noobslab/themes'

    # VLC daily
    - 'ppa:videolan/master-daily'

    # mpv
    - 'ppa:mc3man/mpv-tests'

    # guayadeque
    - 'ppa:anonbeat/guayadeque'

    # handbrake (not updated for artful yet)
    # - 'ppa:stebbins/handbrake-releases'
  become: yes

- name: install dev/prereq packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - curl
    - stow
    - autoconf
    - autoconf-doc
    - build-essential
    - libtool
    - pkg-config
    - cmake
    - ntfs-3g
    - libncurses5-dev
    - libssl-dev
    - libcurl4-openssl-dev
    - unzip
    - mosh
  become: yes

- name: install programming language(s) / compilers
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - openjdk-11-jdk-headless
    - python2.7
    - python-pip
    - python3-pip
  become: yes

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - ubuntu-restricted-extras
    - ppa-purge
    - chromium-browser
    - gnome-tweak-tool
    - numix-icon-theme
    #- numix-icon-theme-circle
    - numix-gtk-theme
    - indicator-multiload
    - ffmpeg
    - chrome-gnome-shell
    - gnome-todo
    - gnome-calendar
    - gnome-mpv
    - guayadeque
    - mkvtoolnix
  become: yes

- name: install python packages
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    # required for tasd.py
    - bs4
    - pycurl
    - mutagen
    - lxml

- name: enable sudo insults
  lineinfile:
    path: /etc/sudoers
    insertafter: '^Defaults'
    line: 'Defaults insults'
    state: present
    validate: '/usr/sbin/visudo -cf %s'
  become: yes

- name: install private keys
  block:
    - file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
    - copy:
        src: "{{ role_path }}/files/id_rsa"
        dest: "{{ ansible_env.HOME }}/.ssh/id_rsa"
        mode: 0600
        owner: "{{ ansible_env.USER }}"
    - copy:
        src: "{{ role_path }}/files/id_rsa.pub"
        dest: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
        mode: 0600
        owner: "{{ ansible_env.USER }}"

- name: install patched Hack font
  block:
    - get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v1.2.0/Hack.zip
        dest: "{{ download_dir }}/Hack.zip"
    - file:
        path: "{{ ansible_env.HOME }}/.fonts"
        state: directory
    - command: "unzip -u {{ download_dir }}/Hack.zip -d {{ ansible_env.HOME }}/.fonts"
    - command: fc-cache -f -v

- import_tasks: system.yml
  when: desktop
- import_tasks: desktop.yml
  when: desktop
  tags: desktop
- import_tasks: zsh.yml
  tags: zsh
- import_tasks: tmux.yml
  tags: tmux
- import_tasks: neovim.yml
- import_tasks: wine.yml
- import_tasks: installs.yml
  tags: installs
- import_tasks: dotfiles.yml
  tags: dotfiles
- import_tasks: beets.yml
- import_tasks: rust.yml
  tags: rust
- import_tasks: ffmpeg.yml
  tags: ffmpeg
