- name: Auto-mount extra drives
  block:
    - mount:
        path: /media/Media
        src: LABEL=Storage
        fstype: ntfs-3g
        opts: default
        state: mounted

    - mount:
        path: /media/StorageOS
        src: LABEL=StorageOS
        fstype: ntfs-3g
        opts: default
        state: mounted

    - mount:
        path: /media/Videos
        src: LABEL=Data04
        fstype: ntfs-3g
        opts: default
        state: mounted
  become: yes

- name: Symlink home dirs
  block:
    - file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: absent
      with_items:
        - Documents
        - Pictures
        - Videos
        - Music
    - file:
        path: "{{ ansible_env.HOME }}/{{ item.name }}"
        src: "{{ item.src }}"
        state: link
      with_items:
        - { name: Documents, src: "/media/StorageOS/Documents" }
        - { name: CalibreLibrary, src: "/media/StorageOS/Books/CalibreLibrary" }
        - { name: Development, src: "/media/StorageOS/Development" }
        - { name: Pictures, src: "/media/Media/Aidan/Pictures" }
        - { name: Music, src: "/media/Media/Aidan/Music" }
        - { name: Videos, src: "/media/Videos/Videos" }
