- name: add wine apt-key
  apt_key:
    url: https://dl.winehq.org/wine-builds/Release.key
    state: present
  become: yes

- name: add wine repository
  apt_repository:
    repo: 'deb https://dl.winehq.org/wine-builds/ubuntu/ artful main'
    state: present
  become: yes

- name: install wine
  apt:
    name: 'winehq-devel'
    install_recommends: yes
    state: latest
    update_cache: yes
  become: yes

- name: download winetricks
  get_url:
    url: 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
    dest: "{{ local_bin_dir }}/winetricks"
    mode: 0755
