- name: check zsh installed
  shell: 'command -v zsh || which zsh'
  register: zsh_cmd
  ignore_errors: yes
  check_mode: no

- debug:
    msg: "{{ zsh_cmd }}"

- block:
  - name: get zsh repository
    git:
      repo: 'git://git.code.sf.net/p/zsh/code'
      dest: "{{ ansible_env.HOME }}/Applications/zsh"
      version: 'tags/zsh-{{ zsh_version }}'

  - name: install yodl for zsh documentation
    apt:
      name: 'yodl'
      state: latest
    become: yes

  - name: zsh preconfig
    command: "{{ ansible_env.HOME }}/Applications/zsh/Util/preconfig"

  - name: zsh configure
    command: "{{ ansible_env.HOME }}/Applications/zsh/configure"

  - name: zsh make
    make:
      chdir: "{{ ansible_env.HOME }}/Applications/zsh"
      params:
        NUM_THREADS: 4

  - name: zsh make install
    make:
      chdir: "{{ ansible_env.HOME }}/Applications/zsh"
      target: install
    become: yes

  when: zsh_cmd.rc == 1

- name: find zsh
  shell: 'command -v zsh || which zsh'
  register: zsh_cmd
  check_mode: no

- debug:
    msg: "{{ zsh_cmd }}"

- name: add zsh to /etc/shells
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_cmd.stdout }}"
  become: yes

- name: update user shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_cmd.stdout }}"
  become: yes

- name: install oh-my-zsh
  shell: 'sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"'
  when: zsh_cmd.rc == 0
